name = "trailsense"
compatibility_date = "2024-06-01"

# If you are only using Pages + D1, you only need the below in your Wrangler config file to interact with D1 locally.
[[d1_databases]]
binding = "DB" # Should match preview_database_id
database_name = "trailsense"
database_id = "68f8e38e-7d48-4a57-9277-0f3653ef2dc4" # wrangler d1 info YOUR_DATABASE_NAME
preview_database_id = "DB" # Required for Pages local development
migrations_dir="db/migrations"